[package]
name = "aosc-findupdate"
version = "0.1.0"
authors = ["liushuyu <liushuyu011@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies", "blocking"] }
regex = "1.4"
rayon = "1.5"
anyhow = "1.0"
serde = "1.0"
version-compare = "0.0.11"
percent-encoding = "2.1"
kuchiki = "0.8"
